### ISSUE TITLE
Remove the "Prevent Towny-Block-Glitching" feature in TownyCombat

### ISSUE THREAD

**Issue by Caleston** [TownyAdvanced/TownyCombat#131]
TownyCombat shouldn't be used for fixing Towny glitches, such should be included in Towny itself. It makes little sense that this fix would only be a part of TownyCombat. 
If the ruse was to try to entice Towny servers to use this plugin by including a glitch fix to it, then I think that card was already used a long time ago. It should be time to include this to full Towny already.

Alternatively, as LlmDl stated in https://github.com/TownyAdvanced/Towny/issues/7095 that "I have always thought this was something reserved to an anti-cheat plugin.": TownyCombat is not an anti-cheat plugin either, so why is such a Towny block glitch fix in a combat plugin in the first place.

**Comment by LlmDl** [comment]
It is a part of TownyCombat because Goosius thought it was a good thing to put into TownyCombat.

If you like my software you should be sponsoring my work. As I have told you repeatedly. Only about 1% of servers are sponsoring and it is unsustainable. When that gets to 3-4% I will be open to doing things for people who are not sponsoring.
